### PR TITLE
Doc/#65 move gh pages to develop

### PR DESCRIPTION
**Pull request by francis-pouatcha**

### CODE REVIEW

**Comment by francis-pouatcha** [comment]
Diagrams are still referenced from gh-pages. Changes will be made to point to develop once diagrams merged into develop.

**Comment by DG0lden** [comment]
Travis refuses to build the branch, that contain `gh-pages` in branch name. I propose to merge this branch to develop manually. @max402 @electronicpeter pls approve

**Comment by electronicpeter** [comment]
As I understood Tarkan, the branch is build -> https://travis-ci.com/adorsys/open-banking-gateway (current)
and as I understood Maksym, the pr can only be completed by francis

**Comment by electronicpeter** [comment]
ok, I am going to rename the branch.
Peter

**Pull request closed without merging**
